### ISSUE TITLE
googleアプリでKPTerのLPのアニメーションがスクロール中に動作しない

### ISSUE THREAD

**Issue by hanaori** [HanaLucky/KPTer-web#11]
現在iPhoneで表示した時の速度が遅いため、表示速度を調整する。

**Comment by hanaori** [comment]
- SPで読み込み速度が遅い原因
  - スクロールをやめないと表示されないため
- 解決方法
  - SPではscrollRevealさせない？

**Comment by luckyriver0** [comment]
googleのスマホアプリだけ、スクロール中にアニメーションが動作しない。
スマホアプリのchrome、safariはスクロール中動作する。

スマホはアニメーションさせないようにしたいが、レスポンシブなので制御は困難。
逆に、動作するようにすることの対応も困難。
見れないわけではないので、対応はなしにしたい所存。
