### ISSUE TITLE
カイゼン

### ISSUE THREAD

**Issue by luckyriver0** [HanaLucky/KPTer-web#13]
- [x] ファーストビューの「ABOUT KPTER」ボタンのオンフォーカス時の色を明るくする
- [x] 各種リンクをタップすると色が暗くなるようにする（押した感触をつくる）

**Comment by hanaori** [comment]
ABOUT KPTER
* どちらかというと、押したときの色だった

押した感
* 各種リンクと言うのはAppストアの画像
* 透明度をあげるイメージ

**Comment by luckyriver0** [comment]
問題なかった。
修正していたのか勘違いだったのか。スミマセヌ。
