### ISSUE TITLE
androidでハンバーガーメニューが動かない

### ISSUE THREAD

**Issue by luckyriver0** [HanaLucky/KPTer-web#16]
### はじめに
機種、OS、ブラウザの確認

### 動かない機種・OS・ブラウザはどれだ？
動かないやつ

動くやつ
Galaxy S | Android5.0 | 標準ブラウザ/chrome/ff
Xperia | Android4.4.4 | 標準ブラウザ/chrome
Arrows NX| Android4.2.2 | 標準ブラウザ/chrome
Xperia SO-02F| Android4.4.4 | 標準ブラウザ/chrome
ASUS Zenfone | Android4.4.2 |  標準ブラウザ/chrome

###  対応策を模索

**Comment by hanaori** [comment]
どうやら動いたらしいでございます。閉じさせていただきます。
