### ISSUE TITLE
design of sign up page

### ISSUE THREAD

**Issue by luckyriver0** [HanaLucky/KPTer-web#186]
![2017-06-17 23 53 38](https://user-images.githubusercontent.com/16001636/27253898-36451624-53b8-11e7-8644-43fe96d07faf.png)

**Comment by hanaori** [comment]
- User名はデフォルトでAnonymousを入れておいて、入力は必須にする
- どの値が入力必須かわかりやすいといいかも

**Comment by luckyriver0** [comment]
このようなイメージ。気になるところ、こうしたいと思うところあればコメントくださーい！

![2017-06-24 12 08 10](https://user-images.githubusercontent.com/16001636/27505242-e4be6b16-58d5-11e7-8bce-115d8857f694.png)

**Comment by luckyriver0** [comment]
- usernameはnicknameに変更
- nicknameのデフォルトは表示しないで必須にする
