### ISSUE TITLE
ボード｜デザイン適応

### ISSUE THREAD

**Issue by hanaori** [HanaLucky/KPTer-web#190]
- 再読込時は `updated_at`で並べる。
- KpCard -> TCard順
- KPT中は自分が１番最近触ったものが１番上にくるようにする

**Comment by luckyriver0** [comment]
@hanaori 
[こちらの画面](https://mdbootstrap.com/live/_MDB/templates/Admin/home%20v3.html)の右下にアクションボタンがぴったりかもしれない

↓を追記すれば（たぶん）表示されるかと思われる！
```
<%= render :partial => 'shared/fixed_action_btn'
```

see. 
https://github.com/HanaLucky/KPTer-web/pull/194/files#diff-1eb477d8fc9e9214596ecee98792b443
