### ISSUE TITLE
Apple Storeに英語の情報を追加する

### ISSUE THREAD

**Issue by hanaori** [HanaLucky/KPTer-web#24]
## Task
- [ ] 英語のバージョンを追加
- [ ] プライマリ言語を英語にする
## 参考資料
- [【iOSアプリ】AppStoreでの表示を多言語化・プライマリ言語の変更](https://islog.tokyo/appstore-localize/)

**Comment by luckyriver0** [comment]
#23 ページ言語をどうするか で仕切り直し。一旦クローズしましたー
