### ISSUE TITLE
トップページ作成

### ISSUE THREAD

**Issue by luckyriver0** [HanaLucky/KPTer-web#242]

**Comment by luckyriver0** [comment]
良さそうなテンプレを見ながら、テンプレ使うか自分たちで作るか検討

良さそうなテンプレ（探し中）
- https://creativemarket.com/ThemeStreet.Net/28603-Fun-Fun-Responsive-HTML5-Template

**Comment by luckyriver0** [comment]
以下購入
regularライセンス
https://themeforest.net/item/thedocs-online-documentation-template/13070884?s_rank=21

**Comment by luckyriver0** [comment]
# フッターについて
## コピーライト
「万国著作権条約」にのみ加盟している国では©️が記載されていないと著作物としての条件を満たさないのだが、一方で著作権に関する「ベルヌ条約」というものもあり、こちらはその必要がない。2015年くらいまではラオス、カンボジアが「万国著作権条約」のみ加盟していたが、今現在は両国とも「ベルヌ条約」に加盟している。

### 必要？
著作権保護の観点からするともはや不要。
だが、各サービスがこれを書いている理由は以下とのこと。
> ひとつは、著作権者を明記し主張することで、無断利用への抑止力となるから。
> もうひとつは、そういう慣習になってしまっているからなんです。

KPTERもこれに習おうと思う。

### KPTERの表記
以下でいこうかと。
KPTER © 2017-(現在年)

### 参考
LIGの記事がわかりやすい→[LINK](https://liginc.co.jp/designer/archives/11313)

**Comment by luckyriver0** [comment]
- [ ] TOP背景画像の差し替え
- [ ] SP表示のセクションタイトルの寄せ
- [ ] セクションの内容になりそうなものをいくつかピックアップする
- [ ] スマホアプリの導線を置く
- [ ] TOP キャッチコピーをいくつか挙げる
- [ ] Featuresどうするか（なくてもいいかもね）
- [ ] フッターリンクなにいれるか。Terms、Contact、Privacy policyくらいでいいかも。

**Comment by luckyriver0** [comment]
- [ ] TOP背景画像の差し替え
    - 「meeting」「team」をキーワードにhttps://creativemarket.com/ から検索。KPTERに当てたイメージは以下。個人的に好きなのを◉つけて見た。
    - https://creativemarket.com/ffforn/1602967-Teamwork
![part1](https://user-images.githubusercontent.com/16001636/35778234-c49a7ec6-09fe-11e8-968c-9dec4485bd27.png)
    - ◉https://creativemarket.com/rawpixel.com/1824721-Colleagues-in-Office
![part2](https://user-images.githubusercontent.com/16001636/35778241-e1c1fe84-09fe-11e8-83dd-9e171e03985b.png)
    - https://creativemarket.com/Jacoblund/1359387-Corporate-business-team-meeting
![part3](https://user-images.githubusercontent.com/16001636/35778269-544f84d0-09ff-11e8-9cd2-6eab90a6862f.png)
    - https://creativemarket.com/rawpixel.com/1831835-Business-people-in-meeting
![part4](https://user-images.githubusercontent.com/16001636/35778272-58952658-09ff-11e8-977d-7466f6e6937f.png)
    - ◉https://creativemarket.com/undrey/2131691-Team-of-female-managers-discussing-business-strategy-during-briefing-in-office
![part5](https://user-images.githubusercontent.com/16001636/35778274-61fb86e2-09ff-11e8-8bbd-787a7d3c3857.png)
    - https://creativemarket.com/ffforn/1602967-Teamwork
![part6](https://user-images.githubusercontent.com/16001636/35778276-6bcb06ac-09ff-11e8-9e42-0af00fe6a3b9.png)
    - ◉こんなんとかも
![part7](https://user-images.githubusercontent.com/16001636/36009235-a77b7672-0d8e-11e8-83de-8ddf9ad0527f.png)
![2018-02-09 12 07 00](https://user-images.githubusercontent.com/16001636/36009895-cada8a38-0d91-11e8-8ab4-0c5e3a13396f.png)
http://www.iconarchive.com/show/small-n-flat-icons-by-paomedia/post-it-icon.html
![2018-02-09 12 09 34](https://user-images.githubusercontent.com/16001636/36009943-1ead7562-0d92-11e8-8375-c030d93f5cc1.png)
労力がものすごいかもしれないけど、一枚一枚を付箋に見立てて、文字の代わりにその状況の写真を当ててみてもいいなと思った。Keep、Problemの状況写真というか。
  - [ ] 女性でKPT感でている画像を改めて探す

最終的には以下の画像にした。気が変わったらまた
![2018-02-11 19 38 59](https://user-images.githubusercontent.com/16001636/36072453-4e2f4dd8-0f63-11e8-9700-e340569dd4a9.png)

購入元：https://creativemarket.com/WavebreakPremium/1752027-Young-creative-business-people

**Comment by luckyriver0** [comment]
- [ ] Top （enの場合、スマホアプリはOnly Japan的な文言をだす。リンクは活性化してていいと思われ、リンク先のapp storeでダウンロードできるかどうかは分かれる）

**Comment by luckyriver0** [comment]
### 誰向けなのか
 - KPTを知っている人
 - チームを改善したい人
　→チームを改善する文化を根付かせる方法

#### キャッチコピー
 - 理想のチームをKPTERで実現しよう
 - 超速改善
 - チームでの振り返りしてますか
 - KPTでの振り返り、はじめませんか？（現状）
 - Online KPT Tool
 - やがて、文化にかわるもの
 - 価値ある、振り返り
 - KPTでチームを笑顔に
 - Leading Your Team
 - チームの改善が、プロダクトの未来に繋がる

**Comment by luckyriver0** [comment]
- [ ] Online KPT @hanaori 
- [ ] Task Management @luckyriver0
- [ ] Reduce Costs

**Comment by hanaori** [comment]
Online KPT
```
いつでもどこでもリアルタイムでKPTをし、仲間と課題を共有することが可能です。
付箋の移動や書き込みが即座に反映され同じ空間にいるような臨場感を感じられます。
リモートワークをしていても同じ画面を共有して課題解決に取り組むことができます。
```
画像の作成に使えそう↓
http://degitekunote.com/wp-content/uploads/2016/10/002-20161030-mavbookpro15.png

**Comment by luckyriver0** [comment]
Task Management ってほどの管理はできないっぽい

```
Share work to be done
（タスクの分担）
Tryは自動的にタスクに記録されチームごとに集約されます。
さらに、タスクのアサインが誰かに偏っていないか可視化することが可能です。
タスクを分担する目安となり完璧なチームワークを実現することができます。
```

**Comment by luckyriver0** [comment]
Reduce Costs
```
付箋、ペン、ホワイトボードを準備する必要はありません。
いつも無くなる付箋やペン、そのような状況もこれでお別れできます。
微々たるものですが備品を発注する手間と費用も削減できます。
```
