### ISSUE TITLE
Let's Encryptを自動で更新させる

### ISSUE THREAD

**Issue by hanaori** [HanaLucky/KPTer-web#32]
- 有効期間が９０日間
- 証明書の更新が行えるのは有効期限が残り少ない証明書（デフォルトでは残り３０日未満）
- 有効期限は証明書更新時間の1時間前から開始

以上を踏まえて、rootユーザーのcrontabに週次(月曜とか)でAM1:05に起動するように設定する。
以下の一連のコマンドを&&で一行にしてコマンドが流れるようにしcronに設定するもよし。shellにして呼び出してもよし。

```
# ディレクトリ移動
cd /usr/local/bin/certbot/

# 更新実行 この結果は標準出力されるので、ほっとくと/var/log/syslogに出力されちゃうからlogとしてどこかに出力したい。
./certbot-auto renew

# apache graceful
service httpd graceful
```

■ 参考URL
https://www.evernote.com/shard/s622/nl/2147483647/0d7f5bf9-4d44-4606-bb2f-ae4d94aa86d2/

**Comment by luckyriver0** [comment]
> rootユーザーのcrontabに週次(月曜とか)でAM1:05に起動するように設定する。

について、以下のように設定した。
```
# crontab -l
5 1 1 * * root /usr/local/bin/certbot/certbot-auto renew --debug && service httpd graceful >> /var/log/certbot-renew.log 2>&1
```
