### ISSUE TITLE
No Kiddingページがほしい

### ISSUE THREAD

**Issue by hanaori** [HanaLucky/KPTer-web#71]
### ページの用途

ありえないことが起こった際のエラー文言を表示するページ。
例）コミュニティに参加済の人がまたその参加に参加するアクションをしたときに表示
### イメージ

![image](https://cloud.githubusercontent.com/assets/7506598/18605245/766fb06a-7cc7-11e6-817f-26eead025f0b.png)
Are you sure that you want to join this community AGAIN??? (NO WAY!)

**Comment by luckyriver0** [comment]
#205 design of error pages に集約しまーす。これはクローズ
